### ISSUE TITLE
Excessvie space usage

### ISSUE THREAD

**Issue by Findarato** [hvalev/isp-pollution-docker#1]
I have this running on a Raspberry pi 3 on a 32GB card and after 8 days the card was filled and the problem was the docker image.  Is there a way to have it not use so much space?

**Comment by hvalev** [comment]
Hi, perhaps it's due to docker logs. The image itself should not store data. I'll need to take a look.

**Comment by hvalev** [comment]
I have tested it myself and could not reproduce the behavior. If it is indeed the container, please provide logs from the docker daemon.
